export const actionTypes = {
  // CHAPTER
  CHAPTER_UNLOCK: 'CHAPTER_UNLOCK',

  // CHARACTER
  CHARACTER_UNLOCK: 'CHARACTER_UNLOCK',
  CHARACTER_ADD_TO_MAP: 'CHARACTER_ADD_TO_MAP',

  // PLACE
  PLACE_UNLOCK: 'PLACE_UNLOCK',

  // PROGRESS
  PROGRESS_INCREMENT_CHAPTER: 'PROGRESS_INCREMENT_CHAPTER',
  PROGRESS_CURRENT_OFFSET: 'PROGRESS_CURRENT_OFFSET',

  // SET DATA FROM API & STORAGE
  SET_PLACELIST: 'SET_PLACELIST',
  SET_CHARACTERLIST: 'SET_CHARACTERLIST',
  SET_CHAPTERLIST: 'SET_CHAPTERLIST',
  SET_PROGRESS: 'SET_PROGRESS',

}
