export const actionTypes = {
  // CHAPTER
  CHAPTER_UNLOCK: 'CHAPTER_UNLOCK',

  // CHARACTER
  CHARACTER_UNLOCK: 'CHARACTER_UNLOCK',

  // SKILL
  SKILL_UNLOCK: 'SKILL_UNLOCK',

  // PLACE
  PLACE_UNLOCK: 'PLACE_UNLOCK',

  // PROGRESS
  PROGRESS_INCREMENT_CHAPTER: 'PROGRESS_INCREMENT_CHAPTER',
  PROGRESS_CURRENT_OFFSET: 'PROGRESS_CURRENT_OFFSET',

  // SET DATA FROM API & STORAGE
  SET_PLACELIST: 'SET_PLACELIST',
  SET_CHARACTERLIST: 'SET_CHARACTERLIST',
  SET_CHAPTERLIST: 'SET_CHAPTERLIST',
  SET_SKILLLIST: 'SET_SKILLLIST',
  SET_SKILLTYPELIST: 'SET_SKILLTYPELIST',
  SET_PROGRESS: 'SET_PROGRESS',

}
