export const actionTypes = {
  // CHAPTER
  CHAPTER_UNLOCK: 'CHAPTER_UNLOCK',

  // CHARACTER
  CHARACTER_UNLOCK: 'CHARACTER_UNLOCK',
  CHARACTER_ADD_TO_MAP: 'CHARACTER_ADD_TO_MAP',

  // PLACE
  PLACE_UNLOCK: 'PLACE_UNLOCK',

  // PROGRESS
  PROGRESS_INCREMENT_CHAPTER: 'PROGRESS_INCREMENT_CHAPTER',
  PROGRESS_INCREMENT_SLIDE: 'PROGRESS_INCREMENT_SLIDE',

  // API
  GET_PLACELIST: 'GET_PLACELIST',
  GET_CHARACTERLIST: 'GET_CHARACTERLIST',
  GET_CHAPTERLIST: 'GET_CHAPTERLIST',

}
